;;anything
(let ((original-browse-url-browser-function browse-url-browser-function))
  ;(el-get 'sync '(anything))
  (require 'anything-startup)
  (require 'anything-config)
  (anything-set-anything-command-map-prefix-key
   'anything-command-map-prefix-key "C-c C-<SPC>")
  (define-key global-map (kbd "C-x b") 'anything-buffers-list)
  (define-key global-map (kbd "C-x g") 'anything-imenu)
  (define-key global-map (kbd "M-y") 'anything-show-kill-ring)
  (define-key global-map (kbd "M-x") 'anything-M-x)
  (define-key global-map (kbd "C-x C-f") 'anything-find-files)
  (define-key anything-map (kbd "C-l") 'anything-execute-persistent-action)
  (define-key anything-map (kbd "C-M-n") 'anything-next-source)
  (define-key anything-map (kbd "C-M-p") 'anything-previous-source)
  (setq browse-url-browser-function original-browse-url-browser-function))
